# https://swagger.io/docs/specification/2-0
swagger: "2.0"

info:
  version: "1.0.0"
  title: "GeoPick API documentation (Swagger)"
  description: "List of API endpoints"

host: 127.0.0.1:8085 
basePath: /v1
schemes:
  - http

paths:
# API metadata
  /version:
    get:
      tags:
        - "API metadata"
      summary: "Returns the API version"      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                version:
                  type: string
        400:
          description: "Could not retrieve the API's version."  

# User authentication
  /authenticate:
    post:
      tags: 
        - "User authentication"
      summary: "Provides a token valid for use against endpoints needing authentication."
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: "access data"
          in: body
          description: "JSON data for the api"
          required: true
          schema:
            type: object
            properties: 
              username: 
                type: string          
                description: "Valid username of registered user"
              password:
                type: string
                description: "Valid password of registered user"
      responses:
        400:
          description: "No user with these credentials exist"
        200:
          description: "Authentication successful"

  /user:
    post:
      tags:
        - "User authentication"
      summary: "Creates a regular user in the database."
      consumes:
        - application/json
      parameters:
        - in: body
          name: UserData
          description: "JSON data for the API"
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: "User created"
          content:
            application/json:
              schema:
                msg:
                  type: string
                  description: "A message indicating the status of the operation"
                  example: "Georeference retrieved"
                success:
                  type: boolean                  
                  example: true
        400:
          description: "User could not be created."

# Georeferencing methods
  /georeference-dwc:
    post:
      tags: 
        - "Georeferencing"
      summary: "Calculates a point-radius georeference given a georeference in Darwin Core terms and JSON format."
      description: "Given a georeferenced locality expressed in GeoJSON format, returns a complete point-radius georeference as a GeoJSON object whose keys are named in Darwin Core terms. It also includes a polygonal representation of the smallest enclosing circle."
      consumes:
        - application/json  # Specify the request content type
      produces:
        - application/json
      parameters:
        - in: body
          name: DwC-GeoreferenceData          
          description: "Georeference data in Darwin Core terms from which to calculate the point-radius."
          required: true
          schema:
            type: object
            properties:
              locality: 
                type: string
              type:
                type: string
              georeferencedBy:
                type: string
              georeferenceRemarks:
                type: string      
              features:
                type: object
                properties:
                  id:
                    type: string  # "id" is a string in this case
                  type:
                    type: string  # "type" is assumed to be a string
                  properties:
                    type: object  # "properties" is an object
                  geometry:
                    type: object
                    properties:
                      type:
                        type: string  # "type" is a string
                      coordinates:
                        type: array
                        items:
                          type: array
                          items:
                            type: number  # Coordinates are represented as numbers
            
      responses:
        200:
          description: "OK"
        400:
          description: "Point-radius calculation failed."  
  
  /georeference:
    post:
      tags: 
        - "Georeferencing"
      summary: "Writes a locality point-radius georeference to the database."
      description: "Takes a locality point-radius georeference in JSON format and stores it in the database. The georeference can later be retrieved using the endpoint '/georeference/{locationid}'"
      consumes:
        - application/json  # Specify the request content type
      produces:
        - application/json  # A response JSON in the form {"success": True, "msg": "Georeference created", "locacationid": georef.id } 
      parameters:
        - in: body
          name: GeoreferenceDB          
          description: "Point-radius georeference to be written into the database."
          required: true
          schema:
            type: object
            properties:
              locationid:
                type: string 
              georef_data:
                type: object
                properties:
                  locationID:
                    type: string
                  locality:
                    type: string
                  decimalLatitude:
                    type: string
                  decimalLongitude:
                    type: string
                  geodeticDatum:
                    type: string
                  coordinateUncertaintyInMeters:
                    type: string
                  coordinatePrecision:
                    type: double
                  pointRadiusSpatialFit:
                    type: string
                  footprintWKT:
                    type: string
                  footprintSRS:
                    type: string
                  footprintSpatialFit:
                    type: number
                  georeferencedBy:
                    type: string
                  georeferencedDate:
                    type: string
                  georeferenceProtocol:
                    type: string
                  georeferenceSources:
                    type: string
                  georeferenceRemarks:
                    type: string
                  shareLink:
                    type: string
                  sec_representation:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        properties:
                          type: object
                        geometry:
                          type: object
      responses:
        200:
          description: "OK"
        400:
          description: "Could not write georeference to the database."  

  /georeferences/{locationid}:
    get:
      tags: 
        - "Georeferencing"
      summary: "Gets a point-radius georeference with id equal to locationid"
      parameters:
        - in: path
          name: locationID
          description: "Location identifier"
          required: true          
          type: string
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                data:
                  type: string
                  description: "A JSON string representing georeferenced data"
                  example: '{"locationID": "geopick-v2.0.0-2024-03-05T11-36-43.359Z-651", "locality": "ss", "decimalLatitude": "57.6962222", "decimalLongitude": "-47.6170809", "geodeticDatum": "EPSG:4326", "coordinateUncertaintyInMeters": "1341393", "coordinatePrecision": 1, "pointRadiusSpatialFit": "", "footprintWKT": "LINESTRING (-67.675781 53.435719, -24.785156 58.263287)", "footprintSRS": "EPSG:4326", "footprintSpatialFit": "", "georeferencedBy": "ss", "georeferencedDate": "2024-03-05T11:36:43.361Z", "georeferenceProtocol": "Georeferencing Quick Reference Guide (Zermoglio et al. 2020, https://doi.org/10.35035/e09p-h128)", "georeferenceSources": "GeoPick v.2.0.0", "georeferenceRemarks": "", "shareLink": "http://geopick.gbif.org/?locationid=geopick-v2.0.0-2024-03-05T11-36-43.359Z-651", "sec_representation": [{"type": "Feature", "properties": {}, "geometry": {"type": "Polygon", "coordinates": [[[-25.677924, 56.003855], ...]]}}]}'
                msg:
                  type: string
                  description: "A message indicating the status of the operation"
                  example: "Georeference retrieved"
                path:
                  type: string
                  description: "The path of the request"
                  example: "/?share=geopick-v2.0.0-2024-03-05T11-36-43.359Z-651"
                success:
                  type: boolean
                  description: "Indicates whether the operation was successful"
                  example: true
        400:
          description: "There is no georeference with such locationID"

  /georeferences:
    get:
      tags: 
        - "Georeferencing"
      summary: "Gets a paged list of georeferences in GeoPick's database"
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                results:
                  type: array
                  properties:
                pagination:
                  type: object
                  properties:
                    count:
                      type: integer
                    page:
                      type: integer
                    per_page:
                      type: integer
                    pages:
                      type: integer
                    results:
                      type: array
                      items:
                        type: object
                        properties:
                          id: 
                            type: integer
                          locationid:
                            type: string
                          time_created:
                            type: string
                            format: date-time
                            example: "2024-03-05T15:35:14.411058+01:00"
                          georef_data:
                            type: object
                            properties:
                              locationID:
                                type: string
                              locality:
                                type: string
                              decimalLatitude:
                                type: string
                              decimalLongitude:
                                type: string
                              geodeticDatum:
                                type: string
                              coordinateUncertaintyInMeters:
                                type: string
                              coordinatePrecision:
                                type: double
                              pointRadiusSpatialFit:
                                type: string
                              footprintWKT:
                                type: string
                              footprintSRS:
                                type: string
                              footprintSpatialFit:
                                type: float
                              georeferencedBy:
                                type: string
                              georeferencedDate:
                                type: string
                              georeferenceProtocol:
                                type: string
                              georeferenceSources:
                                type: string
                              georeferenceRemarks:
                                type: string
                              shareLink:
                                type: string
                              sec_representation:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    type:
                                      type: string
                                    properties:
                                      type: object
                                    geometry:
                                      type: object
                msg:
                  type: string
                  description: "A message indicating the status of the operation"
                  example: "Georeference retrieved"
                path:
                  type: string
                  description: "The path of the request"
                  example: "/?share=geopick-v2.0.0-2024-03-05T11-36-43.359Z-651"
                success:
                  type: boolean
                  description: "Indicates whether the operation was successful"
                  example: true
        400:
          description: "Retrieving of paged list of georeferences failed."

# Endpoints to be used only by the Geopick's web application
  /sec:
    post:
      tags: 
        - "GeoPick's web application private methods"
      summary: "This method is intended to be used only by the GeoPick web application. To directly query the API please refer to the 'georeference-dwc' endpoint."
      consumes:
        - application/json  # Specify the request content type
      produces:
        - application/json
      parameters:
        - in: body
          name: GeoreferenceData
          description: "Georeference data generated by GeoPick's web application."
          required: true
          schema:
            type: object
            properties:
              type: 
                type: string
              geometry:
                type: object
                properties:
                  type:
                    type: string  # "type" is a string
                  coordinates:
                    type: array
                    items:
                      type: array
                      items:
                        type: number  # Coordinates are represented as numbers

      responses:
        200:
          description: "OK"
        400:
          description: "Point-radius calculation failed."  
                                  
                                
