name: Test GeoPick python

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Cache dependency # caching dependency will make our build faster.
      uses: actions/cache@v3 # for more info checkout pip section documentation at https://github.com/actions/cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get -yqq install gdal-bin libgdal-dev g++

    - name: Setup python environment # setting python environment to 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Check Python version # checking the python version to see if 3.x is installed.
      run: python --version

    - name: Install requirements # install application requirements
      run: pip install -r requirements.txt

    - name: Run Test # running tests
      working-directory: ./GeoPick/flask_api
      run: pytest
